#!/bin/bash
# Sigma.Core — project-specific pack hooks (sourced by cpkg)
#
# pre_pack  — called before objects are linked into the package artifact.
#             Bumps SC_CORE_BUILD and regenerates include/sigma.core/version.h.
#             Only fires for the "core" package (the all-inclusive artifact).
#
# post_pack — reserved; currently a no-op.

SC_CORE_VERSION="1.0.0"
SC_BUILD_NUMBER_FILE=".build_number"
SC_VERSION_HEADER="include/sigma.core/version.h"

pre_pack() {
    local pkg="$1"

    # Only the all-inclusive "core" package carries a build number.
    [[ "$pkg" != "core" ]] && return 0

    # Read and increment build number.
    local n=0
    [[ -f "$SC_BUILD_NUMBER_FILE" ]] && n=$(cat "$SC_BUILD_NUMBER_FILE")
    n=$((n + 1))
    echo "$n" > "$SC_BUILD_NUMBER_FILE"

    # Regenerate version header.
    mkdir -p "$(dirname "$SC_VERSION_HEADER")"
    cat > "$SC_VERSION_HEADER" <<HEADER
/*
 * Sigma.Core — auto-generated by pack.sh
 * Do NOT edit manually; regenerated on every: cpkg core
 */
#pragma once

/** Human-readable package version (semver). */
#define SC_CORE_VERSION "${SC_CORE_VERSION}"

/** Monotone build counter — incremented on every cpkg core run. */
#define SC_CORE_BUILD   ${n}
HEADER

    echo "Version: ${SC_CORE_VERSION}+${n} -> ${SC_VERSION_HEADER}"
}

post_pack() {
    local pkg="$1"

    # Only the all-inclusive "core" package needs to sync flat header copies.
    [[ "$pkg" != "core" ]] && return 0

    # Sync namespaced headers to the flat package/include/ layout so that cpub
    # installs them at /usr/local/include/sigma.core/<header>.h (not nested).
    if [ -d "package/include/sigma.core" ]; then
        cp package/include/sigma.core/*.h package/include/
    fi
}
