/*
 * Sigma.Core — auto-generated by pack.sh
 * Do NOT edit manually; regenerated on every: cpkg core
 */
#pragma once

/** Human-readable package version (semver). */
#define SC_CORE_VERSION "1.3.0"

/** Monotone build counter — incremented on every cpkg core run. */
#define SC_CORE_BUILD   20
